const errorTypes = {
    ID_NOT_FOUND_ERROR: 1,
    DUPLICATED_CODE_ERROR: 2,
    NOT_AUTH_TO_CREATE_ERROR: 3,
    NOT_AUTH_TO_DELETE_ERROR: 4,
    NOT_AUTH_TO_MANAGE_USERS_ERROR: 5
}

export default errorTypes